/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator_Exercise;

/**
 *
 * @author miah
 */
public class Calculator_Exercise extends javax.swing.JFrame {

    /**
     * Creates new form Calculator_Exercise
     */
    double Num1, Num2,Result;
    String Op; 
    public Calculator_Exercise() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jtxtDisplay = new javax.swing.JTextField();
        jbtnDivide = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jbtnMulti = new javax.swing.JButton();
        jbtnSeven = new javax.swing.JButton();
        jbtnEight = new javax.swing.JButton();
        jbtnNine = new javax.swing.JButton();
        jbtnMinus = new javax.swing.JButton();
        jbtnFive = new javax.swing.JButton();
        jbtnFour = new javax.swing.JButton();
        jbtnPlus = new javax.swing.JButton();
        jbtnSix = new javax.swing.JButton();
        jbtnOne = new javax.swing.JButton();
        jbtnThree = new javax.swing.JButton();
        jbtnTwo = new javax.swing.JButton();
        jbtnEqual = new javax.swing.JButton();
        jbtnZero = new javax.swing.JButton();
        jbtnMNP = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtDisplay.setColumns(10);
        jtxtDisplay.setFont(new java.awt.Font("Dyuthi", 1, 48)); // NOI18N
        jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDisplay.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 360, 90));

        jbtnDivide.setFont(new java.awt.Font("Gargi", 1, 24)); // NOI18N
        jbtnDivide.setText("/");
        jbtnDivide.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDivideActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 80, 60));

        jbtnClear.setFont(new java.awt.Font("Gargi", 1, 24)); // NOI18N
        jbtnClear.setText("C");
        jbtnClear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 80, 60));

        jbtnBack.setFont(new java.awt.Font("Gargi", 1, 24)); // NOI18N
        jbtnBack.setText("CE");
        jbtnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 80, 60));

        jbtnMulti.setFont(new java.awt.Font("Gargi", 1, 24)); // NOI18N
        jbtnMulti.setText("*");
        jbtnMulti.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMultiActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 80, 60));

        jbtnSeven.setFont(new java.awt.Font("Gargi", 1, 24)); // NOI18N
        jbtnSeven.setText("7");
        jbtnSeven.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSevenActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSeven, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, 60));

        jbtnEight.setFont(new java.awt.Font("Gargi", 1, 24)); // NOI18N
        jbtnEight.setText("8");
        jbtnEight.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEightActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnEight, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 80, 60));

        jbtnNine.setFont(new java.awt.Font("Gargi", 1, 24)); // NOI18N
        jbtnNine.setText("9");
        jbtnNine.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNineActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnNine, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 80, 60));

        jbtnMinus.setFont(new java.awt.Font("Gargi", 1, 24)); // NOI18N
        jbtnMinus.setText("-");
        jbtnMinus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMinusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 80, 60));

        jbtnFive.setFont(new java.awt.Font("Gargi", 1, 24)); // NOI18N
        jbtnFive.setText("5");
        jbtnFive.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFiveActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 80, 60));

        jbtnFour.setFont(new java.awt.Font("Gargi", 1, 24)); // NOI18N
        jbtnFour.setText("4");
        jbtnFour.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFourActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 80, 60));

        jbtnPlus.setFont(new java.awt.Font("Gargi", 1, 24)); // NOI18N
        jbtnPlus.setText("+");
        jbtnPlus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPlusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 80, 60));

        jbtnSix.setFont(new java.awt.Font("Gargi", 1, 24)); // NOI18N
        jbtnSix.setText("6");
        jbtnSix.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSixActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSix, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 80, 60));

        jbtnOne.setFont(new java.awt.Font("Gargi", 1, 24)); // NOI18N
        jbtnOne.setText("1");
        jbtnOne.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOneActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 80, 60));

        jbtnThree.setFont(new java.awt.Font("Gargi", 1, 24)); // NOI18N
        jbtnThree.setText("3");
        jbtnThree.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThreeActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 80, 60));

        jbtnTwo.setFont(new java.awt.Font("Gargi", 1, 24)); // NOI18N
        jbtnTwo.setText("2");
        jbtnTwo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTwoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 80, 60));

        jbtnEqual.setFont(new java.awt.Font("Gargi", 1, 24)); // NOI18N
        jbtnEqual.setText("=");
        jbtnEqual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEqualActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 80, 130));

        jbtnZero.setFont(new java.awt.Font("Gargi", 1, 24)); // NOI18N
        jbtnZero.setText("0");
        jbtnZero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnZeroActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnZero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 80, 60));

        jbtnMNP.setFont(new java.awt.Font("Gargi", 1, 24)); // NOI18N
        jbtnMNP.setText("-/+");
        jbtnMNP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnMNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMNPActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnMNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 80, 60));

        jbtnDot.setFont(new java.awt.Font("Gargi", 1, 24)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnDot.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbtnDot.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 80, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     private void  EnterNumbers(String q){
        String Nums = jtxtDisplay.getText() + q;
        jtxtDisplay.setText(Nums);
     }
     
     
    private void jbtnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSevenActionPerformed
        // TODO add your handling code here:
      EnterNumbers("7");   
    }//GEN-LAST:event_jbtnSevenActionPerformed

    private void jbtnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEightActionPerformed
        // TODO add your handling code here:
        EnterNumbers("8");
    }//GEN-LAST:event_jbtnEightActionPerformed

    private void jbtnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNineActionPerformed
        // TODO add your handling code here:
        EnterNumbers("9");
    }//GEN-LAST:event_jbtnNineActionPerformed

    private void jbtnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFourActionPerformed
        // TODO add your handling code here:
        EnterNumbers("4");
    }//GEN-LAST:event_jbtnFourActionPerformed

    private void jbtnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFiveActionPerformed
        // TODO add your handling code here:
        EnterNumbers("5");
    }//GEN-LAST:event_jbtnFiveActionPerformed

    private void jbtnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSixActionPerformed
        // TODO add your handling code here:
        EnterNumbers("6");
    }//GEN-LAST:event_jbtnSixActionPerformed

    private void jbtnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOneActionPerformed
        // TODO add your handling code here:
        EnterNumbers("1");
    }//GEN-LAST:event_jbtnOneActionPerformed

    private void jbtnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTwoActionPerformed
        // TODO add your handling code here:
        EnterNumbers("2");
    }//GEN-LAST:event_jbtnTwoActionPerformed

    private void jbtnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThreeActionPerformed
        // TODO add your handling code here:
        EnterNumbers("3");
    }//GEN-LAST:event_jbtnThreeActionPerformed

    private void jbtnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnZeroActionPerformed
        // TODO add your handling code here:
        EnterNumbers("0");
    }//GEN-LAST:event_jbtnZeroActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
        // TODO add your handling code here:
//        EnterNumbers(".");
        if(! jtxtDisplay.getText().contains(".")){
            
            jtxtDisplay.setText(jtxtDisplay.getText() + jbtnDot.getText());
        }
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDivideActionPerformed
        // TODO add your handling code here:
//        EnterNumbers("/");
        Num1 = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(" ");
        Op ="/";
    }//GEN-LAST:event_jbtnDivideActionPerformed

    private void jbtnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultiActionPerformed
        // TODO add your handling code here:
//        EnterNumbers("*");
        Num1 = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(" ");
        Op ="*";
    }//GEN-LAST:event_jbtnMultiActionPerformed

    private void jbtnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMinusActionPerformed
        // TODO add your handling code here:
//        EnterNumbers("-");
        Num1 = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(" ");
        Op ="-";
    }//GEN-LAST:event_jbtnMinusActionPerformed

    private void jbtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPlusActionPerformed
        // TODO add your handling code here:
//        EnterNumbers("+");
        Num1 = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(" ");
        Op ="+";
    }//GEN-LAST:event_jbtnPlusActionPerformed

    private void jbtnMNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMNPActionPerformed
        // TODO add your handling code here:
        int nums = Integer.parseInt(String.valueOf(jtxtDisplay.getText()));
        nums = nums*(-1);
        jtxtDisplay.setText(String.valueOf(nums));
        
    }//GEN-LAST:event_jbtnMNPActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        // TODO add your handling code here:
        jtxtDisplay.setText("");
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
       String backspace = null;
       if(jtxtDisplay.getText().length()>0){
           StringBuilder sb = new StringBuilder(jtxtDisplay.getText());
           sb.deleteCharAt(jtxtDisplay.getText().length()-1);
           backspace = sb.toString();
           jtxtDisplay.setText(backspace);
       }
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEqualActionPerformed
        // TODO add your handling code here:
//        Num1, Num2,Result;
     Num2 = Double.parseDouble(jtxtDisplay.getText());
     if("+".equals(Op)){
      Result = Num1 + Num2;
      jtxtDisplay.setText(String.valueOf(Result));
     }
     
     else if("/".equals(Op)){
      Result = Num1 / Num2;
      jtxtDisplay.setText(String.valueOf(Result));
     }
     
     else if("*".equals(Op)){
      Result = Num1 * Num2;
      jtxtDisplay.setText(String.valueOf(Result));
     }
     
     else if("-".equals(Op)){
      Result = Num1 - Num2;
      jtxtDisplay.setText(String.valueOf(Result));
     }
        
    }//GEN-LAST:event_jbtnEqualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator_Exercise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator_Exercise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator_Exercise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator_Exercise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Calculator_Exercise().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnDivide;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnEight;
    private javax.swing.JButton jbtnEqual;
    private javax.swing.JButton jbtnFive;
    private javax.swing.JButton jbtnFour;
    private javax.swing.JButton jbtnMNP;
    private javax.swing.JButton jbtnMinus;
    private javax.swing.JButton jbtnMulti;
    private javax.swing.JButton jbtnNine;
    private javax.swing.JButton jbtnOne;
    private javax.swing.JButton jbtnPlus;
    private javax.swing.JButton jbtnSeven;
    private javax.swing.JButton jbtnSix;
    private javax.swing.JButton jbtnThree;
    private javax.swing.JButton jbtnTwo;
    private javax.swing.JButton jbtnZero;
    private javax.swing.JTextField jtxtDisplay;
    // End of variables declaration//GEN-END:variables
}
